export enum ROLES {
  ADMIN = 'admin',
  USER = 'user',
}

export enum RecordStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
}

export enum UserStatus {
  ACTIVE = 'active',
  LOCKED = 'locked',
  DISABLED = 'disabled',
  PENDING_VERIFICATION = 'pending_verification',
}

export enum AuditEvent {
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_LOGOUT_ALL = 'AUTH_LOGOUT_ALL',
  AUTH_REFRESH = 'AUTH_REFRESH',
  AUTH_REFRESH_REUSE_DETECTED = 'AUTH_REFRESH_REUSE_DETECTED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  SESSION_REVOKED_ALL = 'SESSION_REVOKED_ALL',
  ROLE_CHANGED = 'ROLE_CHANGED',
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  PERMISSIONS_CHANGED = 'PERMISSIONS_CHANGED',
}
